version: '3.7'

services:
    app-vae:
        build: ./VAE
        command: streamlit run VAE/app/Home.py --server.port 8501
        volumes:
            - ./:/usr/src/app
        ports:
            - 8501:8501
        image: yourstreamlitapp:latest
    
    app-balance:
        build: ./balance
        command: streamlit run balance/app/Home.py --server.port 8501
        volumes:
            - ./:/usr/src/app
        ports:
            - 8502:8501
        image: yourstreamlitapp:latest

    app-gait:
        build: ./gait
        command: streamlit run gait/app/Home.py --server.port 8501
        volumes:
            - ./:/usr/src/app
        ports:
            - 8503:8501
        image: yourstreamlitapp:latest